steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/client-image', './client' ]
    id: 'Build Client Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/client-image' ]
    id: 'Push Client Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/server-image', './server' ]
    id: 'Build Server Docker Image'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/server-image' ]
    id: 'Push Server Docker Image'

options:
  logging: CLOUD_LOGGING_ONLY
