apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-cloud-sql-app-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ksa-cloud-sql
      containers:
      - name: backend
        image: europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/backend-image:latest
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: database
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.4
        args:
          - "--structured-logs"
          - "--port=3306"
          - "app-project-431616:europe-west1:mysql-instance"

        securityContext:
          # The default Cloud SQL Auth Proxy image runs as the
          # "nonroot" user and group (uid: 65532) by default.
          runAsNonRoot: true

#        resources:
#          requests:
#            # The proxy's memory use scales linearly with the number of active
#            # connections. Fewer open connections will use less memory. Adjust
#            # this value based on your application's requirements.
#            memory: "4Gi"
#            # The proxy's CPU use scales linearly with the amount of IO between
#            # the database and the application. Adjust this value based on your
#            # application's requirements.
#            cpu: "2"

