apiVersion: v1
kind: Service
metadata:
  name: backend-service
#  labels:
#    service: backend
spec:
  selector:
    app: gke-cloud-sql-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 4000
