# deployment.yml
#apiVersion: apps/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
          # users-app container
          - name: frontend
            image: europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/frontend-image:latest
            # users-app always starts on this port
            ports:
              - containerPort: 3000
          - name: cloudsql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
            command: [ "/cloud_sql_proxy",
                       "-instances=[app-project-431616:europe-west1:mysql-instance]=tcp:3306",
                       "-credential_file=/secrets/cloudsql/credentials.json" ]
            volumeMounts:
              - name: cloudsql-instance-credentials
                mountPath: /secrets/cloudsql
                readOnly: true
            # resource cloudsql needs
            resources:
              requests:
                cpu: "15m"
                memory: "64Mi"
              limits:
                cpu: "20m"
                memory: "128Mi"
        volumes:
          # db credentials stored in this volume to access our mysql
          - name: cloudsql-instance-credentials
            secret:
              secretName: cloudsql-instance-credentials
          - name: cloudsql
            emptyDir:
