apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    service: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
