apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: europe-west1-docker.pkg.dev/app-project-431616/app-docker-repo/client-image:latest
          ports:
            - containerPort: 3000
